### ISSUE TITLE
Named workspaces (with possibly split-monitor-workspaces) behave strangely in ashell

### ISSUE THREAD

**Issue by ds-281** [MalpenZibo/ashell#152]
Hi,

I'm using multiple monitors and come from awesome-wm, so naturally I'm trying to set up a familiar environment. `ashell` looks great. I'm running the last commit (to date: 48122b92991e1917e867dff612f678dbc528e44a).

I've tried to set up the `split-monitor-workspaces` plugin to have 10 workspaces per monitor, and `ashell` displays them almost like I want (relevant bits from the config are `visibility_mode = "MonitorSpecific"` and `enable_workspace_filling = true`).

Here's what it looks like with `ashell`, each monitor has its own set of workspaces and I can move between them independently:
![Image](https://github.com/user-attachments/assets/7438de90-7cbf-4635-b1cf-51feb84cbaff)
![Image](https://github.com/user-attachments/assets/d3910b20-7101-4d76-bb32-f2845a85059d)

However, when I try to set names for my workspaces because why not, such as this:

```
# this is in hyprland.conf
workspace=1,defaultName:foo
workspace=2,defaultName:bar
```

`ashell` hangs at `INFO [ashell::config] Reading config file` and eventually causes hyperland to terminate (seems ultimately caused by a uwsm timeout). I believe this is an `ashell` issue, because when I don't start ashell it works, and if I remove the default names from the configuration it works as well.

I'm new to this ecosystem, so if there's some meaningful logs I can provide, I'll be happy to.

**Comment by MalpenZibo** [comment]
You could try setting the log level in the config file. The logs are under `/tmp/ashell`, sadly, in this case, usually the log doesn't help too much, but maybe we're lucky.

I will try to replicate the issue in the next few days I never try this configuration

**Comment by ds-281** [comment]
Sadly, after setting `log_level = "debug"` in `config.toml` and restarting hyprland, the contents of `ashell_r2025-05-20_09-17-39.log` are probably not going to cut it:
```
INFO [ashell::config] Reading config file
DEBUG [smithay_client_toolkit::registry] Bound new global [58] wl_output v4
DEBUG [smithay_client_toolkit::registry] Bound new global [59] wl_output v4
DEBUG [smithay_client_toolkit::registry] Bound new global [60] wl_output v4
DEBUG [smithay_client_toolkit::registry] Bound new global [9] zxdg_output_manager_v1 v3
DEBUG [smithay_client_toolkit::registry] Bound new global [1] wl_seat v7
DEBUG [smithay_client_toolkit::registry] Bound new global [10] wp_cursor_shape_manager_v1 v1
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Argb8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xrgb8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xbgr8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Abgr8888
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xrgb2101010
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Argb2101010
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Xbgr2101010
DEBUG [smithay_client_toolkit::shm] supported wl_shm format Abgr2101010
```

The journal, however, has an interesting set of entries.
```
May 20 09:17:39 ouiche kernel: upowerd invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=0
May 20 09:17:39 ouiche kernel: CPU: 11 UID: 0 PID: 1257 Comm: upowerd Tainted: G        W          6.14.6-arch1-1 #1 9658fd36a89bb82f508ea2dcbad8e1444239d436
May 20 09:17:39 ouiche kernel: Tainted: [W]=WARN
May 20 09:17:39 ouiche kernel: Hardware name: <REDACTED>
May 20 09:17:39 ouiche kernel: Call Trace:
May 20 09:17:39 ouiche kernel:  <TASK>
May 20 09:17:39 ouiche kernel:  dump_stack_lvl+0x5d/0x80
May 20 09:17:39 ouiche kernel:  dump_header+0x43/0x1aa
May 20 09:17:39 ouiche kernel:  oom_kill_process.cold+0x8/0x8d
May 20 09:17:39 ouiche kernel:  out_of_memory+0x212/0x500
May 20 09:17:39 ouiche kernel:  __alloc_pages_slowpath.constprop.0+0x83d/0xd40
May 20 09:17:39 ouiche kernel:  __alloc_frozen_pages_noprof+0x32a/0x340
May 20 09:17:39 ouiche kernel:  alloc_pages_mpol+0x86/0x170
May 20 09:17:39 ouiche kernel:  folio_alloc_noprof+0x14/0x40
May 20 09:17:39 ouiche kernel:  __filemap_get_folio+0x1cf/0x310
May 20 09:17:39 ouiche kernel:  filemap_fault+0x1fb/0xd90
May 20 09:17:39 ouiche kernel:  __do_fault+0x31/0x1d0
May 20 09:17:39 ouiche kernel:  do_fault+0x34c/0x510
May 20 09:17:39 ouiche kernel:  ? ___pte_offset_map+0x1b/0x180
May 20 09:17:39 ouiche kernel:  __handle_mm_fault+0x7eb/0xfc0
May 20 09:17:39 ouiche kernel:  ? srso_alias_return_thunk+0x5/0xfbef5
May 20 09:17:39 ouiche kernel:  ? seq_read_iter+0x20a/0x470
May 20 09:17:39 ouiche kernel:  handle_mm_fault+0xde/0x2c0
May 20 09:17:39 ouiche kernel:  do_user_addr_fault+0x21e/0x640
May 20 09:17:39 ouiche kernel:  exc_page_fault+0x81/0x1b0
May 20 09:17:39 ouiche kernel:  asm_exc_page_fault+0x26/0x30
May 20 09:17:39 ouiche kernel: RIP: 0033:0x7679c9da866d
May 20 09:17:39 ouiche kernel: Code: Unable to access opcode bytes at 0x7679c9da8643.
May 20 09:17:39 ouiche kernel: RSP: 002b:00007fff923e7660 EFLAGS: 00010287
May 20 09:17:39 ouiche kernel: RAX: 00007679c9ef49e0 RBX: 00005f4c9424d760 RCX: 0000000000000000
May 20 09:17:39 ouiche kernel: RDX: 0000000000000000 RSI: 00005f4c9424d768 RDI: 00007679c9f0f8d4
May 20 09:17:39 ouiche kernel: RBP: 00007fff923e7ae0 R08: 0000000000000008 R09: 00005f4c9424d760
May 20 09:17:39 ouiche kernel: R10: 0000000000000008 R11: 00007679c9ef49e0 R12: 00007679c9f0f8d4
May 20 09:17:39 ouiche kernel: R13: 00007679c9f43da0 R14: 0000000000000000 R15: 0000000000000000
May 20 09:17:39 ouiche kernel:  </TASK>
May 20 09:17:39 ouiche kernel: Mem-Info:
May 20 09:17:39 ouiche kernel: active_anon:40689 inactive_anon:15078505 isolated_anon:0
                                active_file:282 inactive_file:968 isolated_file:0
                                unevictable:8 dirty:0 writeback:0
                                slab_reclaimable:6836 slab_unreclaimable:30766
                                mapped:15577 shmem:18375 pagetables:31140
                                sec_pagetables:1123 bounce:0
                                kernel_misc_reclaimable:0
                                free:87771 free_pcp:328 free_cma:0
May 20 09:17:39 ouiche kernel: Node 0 active_anon:162756kB inactive_anon:60314020kB active_file:1532kB inactive_file:3872kB unevictable:32kB isolated(anon):0kB isolated
(file):0kB mapped:62308kB dirty:0kB writeback:0kB shmem:73500kB shmem_thp:0kB shmem_pmdmapped:0kB anon_thp:2385920kB writeback_tmp:0kB kernel_stack:8032kB pagetables:124560kB sec_pagetables:4492kB all_unr
eclaimable? no
May 20 09:17:39 ouiche kernel: Node 0 DMA free:11264kB boost:0kB min:16kB low:28kB high:40kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB i
nactive_file:0kB unevictable:0kB writepending:0kB present:15996kB managed:15360kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
May 20 09:17:39 ouiche kernel: lowmem_reserve[]: 0 1127 59892 59892 59892
May 20 09:17:39 ouiche kernel: Node 0 DMA32 free:235560kB boost:0kB min:1220kB low:2324kB high:3428kB reserved_highatomic:0KB active_anon:4kB inactive_anon:910560kB act
ive_file:36kB inactive_file:40kB unevictable:0kB writepending:0kB present:1220920kB managed:1154776kB mlocked:0kB bounce:0kB free_pcp:752kB local_pcp:0kB free_cma:0kB
May 20 09:17:39 ouiche kernel: lowmem_reserve[]: 0 0 58764 58764 58764
May 20 09:17:39 ouiche kernel: Node 0 Normal free:104260kB boost:47104kB min:113448kB low:173612kB high:233776kB reserved_highatomic:0KB active_anon:160604kB inactive_a
non:59405608kB active_file:0kB inactive_file:5332kB unevictable:32kB writepending:0kB present:61312000kB managed:60175344kB mlocked:32kB bounce:0kB free_pcp:560kB local_pcp:248kB free_cma:0kB
May 20 09:17:39 ouiche kernel: lowmem_reserve[]: 0 0 0 0 0
May 20 09:17:39 ouiche kernel: Node 0 DMA: 0*4kB 0*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 1*1024kB (U) 1*2048kB (M) 2*4096kB (M) = 11264kB
May 20 09:17:39 ouiche kernel: Node 0 DMA32: 141*4kB (UM) 4*8kB (U) 9*16kB (UM) 7*32kB (U) 3*64kB (U) 1*128kB (U) 3*256kB (U) 2*512kB (U) 3*1024kB (UM) 0*2048kB 56*4096
kB (UM) = 235524kB
May 20 09:17:39 ouiche kernel: Node 0 Normal: 4806*4kB (U) 3389*8kB (UE) 1218*16kB (UE) 1192*32kB (UE) 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 10396
8kB
May 20 09:17:39 ouiche kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
May 20 09:17:39 ouiche kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
May 20 09:17:39 ouiche kernel: 19618 total pagecache pages
May 20 09:17:39 ouiche kernel: 0 pages in swap cache
May 20 09:17:39 ouiche kernel: Free swap  = 0kB
May 20 09:17:39 ouiche kernel: Total swap = 0kB
May 20 09:17:39 ouiche kernel: 15637229 pages RAM
May 20 09:17:39 ouiche kernel: 0 pages HighMem/MovableOnly
May 20 09:17:39 ouiche kernel: 300859 pages reserved
May 20 09:17:39 ouiche kernel: 0 pages cma reserved
May 20 09:17:39 ouiche kernel: 0 pages hwpoisoned
May 20 09:17:39 ouiche kernel: Tasks state (memory values in pages):
May 20 09:17:39 ouiche kernel: [  pid  ]   uid  tgid total_vm      rss rss_anon rss_file rss_shmem pgtables_bytes swapents oom_score_adj name
May 20 09:17:39 ouiche kernel: [    691]     0   691    34175      224      224        0         0   299008        0          -250 systemd-journal
May 20 09:17:39 ouiche kernel: [    708]     0   708     3772      286      224       62         0    73728        0             0 systemd-userdbd
May 20 09:17:39 ouiche kernel: [    737]   976   737     6224      768      768        0         0    90112        0             0 systemd-resolve
May 20 09:17:39 ouiche kernel: [    742]     0   742     8902      547      544        3         0    90112        0         -1000 systemd-udevd
May 20 09:17:39 ouiche kernel: [    914]    81   914     2088      215      169       46         0    61440        0          -900 dbus-broker-lau
May 20 09:17:39 ouiche kernel: [    915]    81   915     1232      228      195       33         0    53248        0          -900 dbus-broker
May 20 09:17:39 ouiche kernel: [    916]     0   916     4234       57       32       25         0    53248        0             0 iwd
May 20 09:17:39 ouiche kernel: [    917]     0   917     4018      360      271       89         0    81920        0             0 systemd-logind
May 20 09:17:39 ouiche kernel: [   1029]  1000  1029     5308      696      672       24         0    81920        0           100 systemd
May 20 09:17:39 ouiche kernel: [   1031]  1000  1031     5684      524      483       41         0    81920        0           100 (sd-pam)
May 20 09:17:39 ouiche kernel: [   1040]  1000  1040    27492      406      384       22         0   122880        0           200 gcr-ssh-agent
May 20 09:17:39 ouiche kernel: [   1058]  1000  1058     2022      118       64       54         0    57344        0           200 dbus-broker-lau
May 20 09:17:39 ouiche kernel: [   1059]  1000  1059     1134      159       96       63         0    53248        0           200 dbus-broker
May 20 09:17:39 ouiche kernel: [   1139]  1000  1139    40943      167      128       39         0    73728        0           200 dconf-service
May 20 09:17:39 ouiche kernel: [   1233]  1000  1233    25853     1493     1432       61         0   106496        0           200 pipewire
May 20 09:17:39 ouiche kernel: [   1235]  1000  1235   120648     1395     1311       84         0   163840        0           200 wireplumber
May 20 09:17:39 ouiche kernel: [   1237]  1000  1237    25119      728      628      100         0    98304        0           200 pipewire-pulse
May 20 09:17:39 ouiche kernel: [   1238]   133  1238     5422      101       32       69         0    57344        0             0 rtkit-daemon
May 20 09:17:39 ouiche kernel: [   1257]     0  1257    79534      768      768        0         0   126976        0             0 upowerd
May 20 09:17:39 ouiche kernel: [   1282]   102  1282    95157      256      256        0         0   102400        0             0 polkitd
May 20 09:17:39 ouiche kernel: [   1453]  1000  1453    42069      201      192        9         0    94208        0           200 at-spi2-registr
May 20 09:17:39 ouiche kernel: [   1495]  1000  1495    38823      133       32      101         0    77824        0           200 gpg-agent
May 20 09:17:39 ouiche kernel: [   2105]  1000  2105    42069      280      192       88         0    86016        0           200 at-spi2-registr
May 20 09:17:39 ouiche kernel: [   2571]  1000  2571    42069      276      192       84         0    86016        0           200 at-spi2-registr
May 20 09:17:39 ouiche kernel: [   7233]  1000  7233    42069      254      192       62         0    81920        0           200 at-spi2-registr
May 20 09:17:39 ouiche kernel: [   7404]     0  7404     3953      258      224       34         0    77824        0             0 systemd-userwor
May 20 09:17:39 ouiche kernel: [   7405]     0  7405     3911      224      224        0         0    73728        0             0 systemd-userwor
May 20 09:17:39 ouiche kernel: [   7491]     0  7491     2322      263      160      103         0    61440        0             0 login
May 20 09:17:39 ouiche kernel: [   7497]  1000  7497     4653      307      224       83         0    86016        0             0 systemctl
May 20 09:17:39 ouiche kernel: [   7512]  1000  7512     1383       77        0       77         0    49152        0           200 waitpid
May 20 09:17:39 ouiche kernel: [   7513]  1000  7513     1383       92        0       92         0    57344        0             0 waitpid
May 20 09:17:39 ouiche kernel: [   7536]  1000  7536   716357    37463    21950       54     15459   937984        0           200 Hyprland
May 20 09:17:39 ouiche kernel: [   7593]  1000  7593 24071284 15040180 15040055      125         0 120967168        0           200 ashell
May 20 09:17:39 ouiche kernel: [   7620]  1000  7620   256003     8885     8852       33         0   319488        0           200 Xwayland
May 20 09:17:39 ouiche kernel: [   7641]  1000  7641    20951      126       96       30         0    73728        0           200 hypridle
May 20 09:17:39 ouiche kernel: [   7643]  1000  7643    44903    18038     7290       92     10656   237568        0           200 hyprpaper
May 20 09:17:39 ouiche kernel: [   7653]  1000  7653   123928     1120     1120        0         0   266240        0           200 hyprpolkitagent
May 20 09:17:39 ouiche kernel: [   7665]  1000  7665   117987      578      512       66         0   159744        0           200 xdg-desktop-por
May 20 09:17:39 ouiche kernel: [   7671]  1000  7671    76440      154       64       90         0    98304        0           200 xdg-permission-
May 20 09:17:39 ouiche kernel: [   7676]  1000  7676   134775      166      128       38         0   139264        0           200 xdg-document-po
May 20 09:17:39 ouiche kernel: [   7682]  1000  7682      641       72        0       72         0    45056        0           200 fusermount3
May 20 09:17:39 ouiche kernel: [   7689]  1000  7689   228005     1728     1728        0         0   217088        0           200 xdg-desktop-por
May 20 09:17:39 ouiche kernel: [   7701]  1000  7701   141863     7924     3060        0      4864   282624        0           200 termite
May 20 09:17:39 ouiche kernel: [   7707]  1000  7707    95138      228      160       68         0    98304        0           200 at-spi-bus-laun
May 20 09:17:39 ouiche kernel: [   7713]  1000  7713     1996      132       64       68         0    61440        0           200 dbus-broker-lau
May 20 09:17:39 ouiche kernel: [   7714]  1000  7714     1033      126       32       94         0    49152        0           200 dbus-broker
May 20 09:17:39 ouiche kernel: [   7716]  1000  7716     2847      656      573       83         0    69632        0           200 zsh
May 20 09:17:39 ouiche kernel: [   7730]  1000  7730    42069      212      160       52         0    81920        0           200 at-spi2-registr
May 20 09:17:39 ouiche kernel: [   7775]     0  7775     3876      266      224       42         0    73728        0             0 systemd-userwor
May 20 09:17:39 ouiche kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=upower.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/session.slice/wa
yland-wm@hyprland.desktop.service,task=ashell,pid=7593,uid=1000
May 20 09:17:39 ouiche kernel: Out of memory: Killed process 7593 (ashell) total-vm:96285136kB, anon-rss:60160220kB, file-rss:500kB, shmem-rss:0kB, UID:1000 pgtables:118132kB oom_s
core_adj:200
May 20 09:17:39 ouiche systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
```

It seems that `ashell` gets OOM-killed.

**Comment by MalpenZibo** [comment]
Ok interesting! I will investigate more

**Comment by ds-281** [comment]
Some update: the fact that I use multiple monitors appears to be irrelevant in a way. Ashell loads further (the bar is displayed) when using just the e-DP1 output but eats up memory until exhaustion after ~10-15 seconds. The log also goes further than the "reading config" part but I have not found anything indicative of an issue there.

However, I've managed to run it through `heaptrack`.
If that is of any help, here's a screenshot of the relevant parts.

![Image](https://github.com/user-attachments/assets/739663fa-b8fe-4e4c-9115-3fae3cf1f47a)

(I ran `killall -STOP ashell` to stop it before it exploded)

**Comment by ds-281** [comment]
All right, some more digging seems to indicate that it's configuration-related. I've removed my `ashell.conf` and it no longer eats up memory.


Sidetrack:
But it does behave very strangely on workspace 2, which is the ws I have renamed in my `hyprland.conf`.
![Image](https://github.com/user-attachments/assets/772c4518-718e-4018-a6cc-f1ba4cbe69ac)

After renaming ws 1 as well:
![Image](https://github.com/user-attachments/assets/99157f15-b77a-4f9f-9974-ec231beb9e91)

**Comment by ds-281** [comment]
I've tracked down the configuration option that causes the memory leak: it's `enable_workspace_filling = true`. Just adding that as my `config.toml` causes the leak, and using my normal config without that option does not cause issues (besides the sidetrack above with workspaces duplicated).

So, to summarize: it appears to be the combination of workspace filling set to enabled, workspaces with default names and _possibly_ the fact that I use the `split-monitor-workspaces` plugin.

**Comment by MalpenZibo** [comment]
This is interesting.

Recently I merged this PR https://github.com/MalpenZibo/ashell/pull/151.
It contains a small refactor of the workspaces module. You could try if It resolves the issue otherwise I will try to fix It before the next release

**Comment by ds-281** [comment]
How convenient! Thank you.

Yep, the leak is gone.



The weird behavior described in the sidetrack is still present but perhaps that's just a compatibility issue with `split-monitor-workspaces`, or even a `split-monitor-workspaces` issue entierly. Does renaming workspaces work with "normal" setups on ashell?

I'll let you close this issue if you think there's no further investigation to be done.

**Comment by MalpenZibo** [comment]
No let's maintain this issue open for now. I prefer at least replicate the issue on my system

**Comment by MalpenZibo** [comment]
ok, I think that the problem could be related to the `split-monitor-workspaces`. I had to try it. Could you paste your Hyperland config related to the workspaces and split monitor workspaces plugin here?

**Comment by ds-281** [comment]
Not much, just this config and a few binds on `split-workspace`, `split-cycleworkspaces` and `split-movetoworkspaceslient` to cycle through the workspaces.

```
plugin {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    split-monitor-workspaces {                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        count = 10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        keep_focused = 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        enable_notifications = 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        enable_persistent_workspaces = 1                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
}   
```

**Comment by MalpenZibo** [comment]
The issue should be fixed with this PR https://github.com/MalpenZibo/ashell/pull/163

**Comment by ds-281** [comment]
Awesome, thank you.

Yes, duplicate workspaces are gone! (For the record, I still cannot rename workspaces, but that's not an ashell issue. Also, nice to see `iwd` support landing!)
